### PR TITLE
Added the op. argument "Fileout"

### PR DESCRIPTION
**Pull request by B00mGit**
By using the --fileout option a user can direct the output to a datetime named file written in the current directory.

### CODE REVIEW

**Comment by B00mGit** [comment]
For my needs I would find it useful to be able to customize the separator character used for the --csv output.
@zertrin Do you think this is a desirable option to include?
If so, should it be customizable to any character or from a choice of maybe 5 or so commonly used characters?
I can include whats needed in this pull if you like??

**Comment by zertrin** [comment]
Hi,

Thanks for this proposition. However I had previously decided not to implement any kind of file writing feature in clikraken. The idea is that if the user wants to get the output in a file, she can just redirect it when calling clikraken.

For example:

    clikraken --csv ohlc > $OUTPUT_FILE_PATH

This leaves the user full choice over the naming scheme and the location where the file is to be written. More importantly, this shifts to the user the responsibility of making sure that there is sufficient permissions to do so.

For the other proposition (customization of the CSV separator), please propose it in a separate issue/PR. I think this is a good idea to implement.

**Comment by B00mGit** [comment]
Okay, yes I suppose that would be the best option. I didn't realise that it was that easy to file out :flushed:
I'll implement the customization of the separator.
Do you think the option should be for a limited set of characters or any character?

**Comment by zertrin** [comment]
I think any character is better. This leaves the most flexibility for the users.

**Comment by zertrin** [comment]
I you don't mind, I'll implement it myself right away

**Comment by B00mGit** [comment]
Yes, no problem.
Thanks

**Comment by zertrin** [comment]
The custom CSV separator has been implemented in version 0.8.1.

You'll notice that you can even use tabs as separators now with `--csvseparator "\t"`.

**Comment by B00mGit** [comment]
Yes, I liked the 'Trick' to be able to use the escape character.
Thx for the update and the mention in the change log.

**Pull request closed without merging**
