### PR TITLE
Add auto volume calculation based on balance and price when placing orders

### PR DESCRIPTION
**Pull request by chrisrichardson77**
I really wanted this feature so I felt the need to code it in!
Create a buy order with:
clikraken place buy auto <price>
New feature will query current balance of the second of the currency pair (eg: EUR for BCHEUR) and will calculate the max volume for the given price.
Similar for sell orders but slightly less useful.

### CODE REVIEW

**Comment by karlandoh** [comment]
Amazing. Has this been implemented yet? Do all we need to do is type "clikraken place buy auto" followed by whatever arguments we want? **Will this also apply for flipping from long to short?**

Thank you and take care.

**Comment by chrisrichardson77** [comment]
@karlandoh The current implementation (in my branch/PR, not merged) queries balances only and does not consider existing orders, so no, I'm afraid flipping long-short wouldn't work. This shortcoming also means that existing orders could result in an "insufficient balance" error from the API. Perhaps fixing those together would be nice, maybe as a follow-up if the PR gets merged.

**Comment by zertrin** [comment]
Sorry, I was on different personal and business trips since end of December and didn't have time to tackle this PR until now.

Since the ArgParse help text _('auto' to query and use relevant balance)_ is a bit short to understand how this functionality works (I personally am not really sure that I understand it properly), can I ask you to update this PR in order to include a short paragraph in the README which explains (and demonstrate) this functionality. 

Please include this explanation after _"Using leverage"_ but before _"Examples in another currency pair"_ and use the same style that I used (explain by commenting different concrete examples, the length of the explanation comment is not really restricted as long as it is readable. But longer explanations can also take place outside of the example code block.).

Please also state any current limitation about this functionality. I am for example thinking about what you mentioned in your [previous comment](https://github.com/zertrin/clikraken/pull/30#issuecomment-366694830), but maybe you know some other limitations.

Thanks in advance!

**Comment by zertrin** [comment]
Closing as I won't be maintaining this project any more.

Thanks though!

**Pull request closed without merging**
