### PR TITLE
Add margin trading support

### PR DESCRIPTION
**Pull request by melko**
This pull request add missing features for a basic margin trading support, namely:
- "leverage" argument for the place subcommand
- new "positions" subcommand, to let the user see his open positions
- new "trade_balance" subcommand, for a short summary of the trading balance

### CODE REVIEW

**Comment by zertrin** [comment]
Thanks a lot for your interest and contribution! I will review it as soon as possible :)

**Comment by zertrin** [comment]
Oh and since I usually don't do margin trading myself, could you provide an example of output for the list position and trade balance commands please?

(you may obfuscate the position IDs, numbers and asset pairs names to protect your privacy, but please keep the format so I can see how it looks like).

**Comment by melko** [comment]
Here's an example output from "clikraken pos":
<pre>ordertxid            posstatus    pair      time                        type    ordertype        cost      fee    vol    vol_closed    margin    value      net  terms                  rollovertm  misc    oflags
-------------------  -----------  --------  --------------------------  ------  -----------  --------  -------  -----  ------------  --------  -------  -------  -------------------  ------------  ------  --------
XXXXXX-QQQQQ-FDSASW  open         XXBTZEUR  2017-07-11 10:49:35.123400  sell    market       95.12344  0.12345  0.017             0  18.12345   74.104  -0.1234  0.0100% per 4 hours    1301827278
</pre>

while here's "clikraken tbal":
<pre>--------------------------------------------  --------
equivalent balance                             12.3456
trade balance                                  23.4321
margin amount of open positions                34.1234
unrealized net profit/loss of open positions   -1.3149
cost basis of open positions                  111.2222
current floating valuation of open positions  112.3333
equity                                         23.4567
free margin                                    -0.1663
margin level                                   99.24
--------------------------------------------  --------
</pre>

**Comment by zertrin** [comment]
Thanks again, I merged into master and this will be part of the next release.

I would like to extend the README with some example of leveraged trading, however as I mentioned I never trade with leverage.

Could you write some examples in the README and submit a Pull Request for that?

Thanks a lot !

**Comment by melko** [comment]
Sure, I'll add some examples in the 'Usage examples' section, though it's just a standard place order plus the leverage flag.
Since I'm on it, I'll rework a bit the output of 'pos' and 'tbal', since now they both use standard dicts, so can happen that it's not always printed in the same order.

**Comment by zertrin** [comment]
Oh indeed, that was something I intended to correct last week when I quickly looked over the diff but forgot to do yesterday when actually merging. 

Thanks!

**Pull request merged**
